config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root to: 'home#index'

  devise_for :users, path:'', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  resources :posts do
    member do
      post :publish
    end
  end

  namespace :admin do
    get '/', to: 'application#index'
    resources :users
    resources :posts
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
# frozen_string_literal: true

class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
# frozen_string_literal: true

class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
# frozen_string_literal: true

class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :header_image, HeaderImageUploader

  belongs_to :user

  before_save :generate_published_at, if: :published

  validates_presence_of :title, :content, :header_image
  validates :header_image, header_image_has_minimum_size: true

  delegate :name, to: :user, prefix: true, allow_nil: true
  delegate :email, to: :user, prefix: true, allow_nil: true

  scope :id_desc, -> { order id: :desc }
  scope :is_published, -> { where published: true }

  def save_as_published
    transaction do
      return true if update(published: true, published_at: Time.current)

      raise ActiveRecord::Rollback
    end
  end

  private
  def generate_published_at
    self.published_at = Time.current
  end
end

app/models/role.rb
class Role < ApplicationRecord
  ROLES = %w(admin regular_user).freeze
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, polymorphic: true, optional: true

  # validates :resource_type,
  #           :inclusion => { :in => Rolify.resource_types },
  #           :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts

  after_create :assign_default_role

  scope :id_desc, -> { order id: :desc }
  scope :regular_users, -> { with_role :regular_user }

  def assign_default_role
    self.add_role(:regular_user) if roles.blank?
  end

  def admin?
    has_cached_role?(:admin)
  end

  def regular_user?
    has_cached_role?(:regular_user)
  end
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ActionController::Base
  include Pundit
  before_action :authenticate_user!

  layout 'admin/layouts/application'

  def index
  end

  private
  def authenticate_user!
    if user_signed_in? && current_user.admin?
      super
    else
      redirect_to root_path, alert: t('admin.errors.unauthenticated')
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ApplicationController
  before_action :set_post, except: [:index, :new, :create]

  def index
    @posts = Post.id_desc.page(params[:page])
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to admin_posts_path, notice: t('.success')
    else
      flash.now[:warning] = t('.error')
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to admin_posts_path, notice: t('.success')
    else
      flash.now[:warning] = t('.error')
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to admin_posts_path, notice: t('.successs')
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :description, :header_image, :content)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  before_action :set_user, except: [:index, :new, :create]

  def index
    @users = User.regular_users.id_desc.page(params[:page])
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: t('.success')
    else
      flash.now[:warning] = t('.error')
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: t('.success')
    else
      flash.now[:warning] = t('.error')
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path, notice: t('.successs')
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password).tap do |p|
      p[:password] = nil if p[:password].blank?
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.is_published.id_desc.page(params[:page])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, except: [:index, :show, :new, :create]
  before_action :authenticate_user!, except: :show

  def index
    @posts = current_user.posts.id_desc.page(params[:page])
  end

  def show
    @post = policy_scope(Post).find(params[:id])
  end

  def new
    @post = current_user.posts.new
  end

  def edit
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to posts_path, notice: t('.success')
    else
      flash.now[:warning] = t('.error')
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path, notice: t('.success')
    else
      flash.now[:warning] = t('.error')
      render :edit
    end
  end

  def publish
    @post.save_as_published
    redirect_to posts_path
  end

  private
  def set_post
    @post = current_user.posts.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :description, :header_image, :content, :published)
  end

  private
  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to root_path, alert: t('errors.unauthenticated')
    end
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  layout 'application_no_sidebar'
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::SessionsController
  layout 'application_authentication'

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      super
    else
      flash.now[:warning] = t('.error')
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  layout 'application_authentication'
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def pagination collection, theme
    paginate collection, theme: theme
  end
end

app/views/admin/application/index.html.slim
h1.mt-4 ADMIN PAGE
ol.breadcrumb.mb-4
  li.breadcrumb-item.active Welcome to Admin Page !

app/views/admin/layouts/application.html.slim
doctype html
html
  head
    title Dashboard - SB Admin
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta charset="utf-8" /
    meta content="IE=edge" http-equiv="X-UA-Compatible" /
    meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport" /
    meta content="" name="description" /
    meta content="" name="author" /
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'admin/application', media: 'all'
    = javascript_include_tag 'admin/application'
    = yield :header
  body.sb-nav-fixed
    = render 'admin/shared/navbar'
    #layoutSidenav
      = render 'admin/shared/sidebar'
      #layoutSidenav_content
        main
          .container-fluid.px-4
            = yield
        = render 'admin/shared/footer'

app/views/admin/posts/_form.html.slim
- content_for(:header) do
  = stylesheet_link_tag 'admin/posts/form', media: 'all'
  = javascript_include_tag Ckeditor.cdn_url
  = javascript_include_tag 'shared/posts/form'

.row
  .col-xl-12
    .card
      .card-body
        = form_with model: [:admin, post], local: true do |f|
          .card-body
            .form-floating.mb-3
              = f.text_field :title, class: 'form-control', placeholder: 'Title', id: 'inputTitle', autocomplete: 'off', required: true
              label for='inputTitle' Title #{post.errors[:title].join('and')}
            .form-floating.mb-3
              = f.text_field :description, class: 'form-control', placeholder: 'Description', autocomplete: 'off', id: 'inputDescription'
              label for='inputDescription' Description #{post.errors[:description].join('and')}
            .form-floating.d-flex.flex-column-reverse.mb-3
              - if post.header_image.present?
                = image_tag post.header_image.thumb.url, class: 'mb-1', id: 'previewImage'
              - else
                img.mb-1#previewImage src="#{asset_path 'default-image.jpg'}"
              = f.file_field :header_image, class: 'form-control pt-1', id: 'inputHeaderImage'
              label.position-static for='inputHeaderImage' Header Image #{post.errors[:header_image].join('and')}
            .form-floating.d-flex.flex-column-reverse.mb-3
              = f.cktext_area :content, class: 'form-control', placeholder: 'Content', autocomplete: 'off', id: 'inputContent', required: true
              label.position-static for='inputContent' Content #{post.errors[:content].join('and')}
            => f.submit 'Submit', class: 'btn btn-primary'
            = link_to 'Back', admin_posts_path, class: 'btn btn-secondary'

app/views/admin/posts/_post.html.slim
tr
  td = post.id
  td = post.user_name
  td = post.user_email
  td = post.title
  td = post.description
  td = l post.published_at, format: :default if post.published
  td
    => link_to 'Show', post_path(post), class: 'btn btn-primary'
    => link_to 'Edit', edit_admin_post_path(post), class: 'btn btn-warning'
    = link_to 'Destroy', admin_post_path(post), class: 'btn btn-danger', data: { confirm: 'Are you ?' }, method: :delete

app/views/admin/posts/edit.html.slim
h1.mt-4 EDIT POST
ol.breadcrumb.mb-4
  li.breadcrumb-item = link_to 'Admin Page', admin_path
  li.breadcrumb-item = link_to 'List Of Posts', admin_posts_path
  li.breadcrumb-item.active Edit Post
= render 'form', post: @post

app/views/admin/posts/index.html.slim
h1.mt-4 LIST OF POSTS
ol.breadcrumb.mb-4
  li.breadcrumb-item = link_to 'Admin Page', admin_path
  li.breadcrumb-item.active List Of Posts
.row
  .col-xl-12
    .card.mb-4
      .card-header
        .float-end
          = link_to 'New Post', new_post_path, class: 'btn btn-primary'
      .card-body
        = pagination @posts, 'bootstrap4'
        .table-responsive
          table.table.table-bordered.table-striped.text-nowrap
            thead
              tr
                th Id
                th User Name
                th User Email
                th Title
                th Description
                th Published at
                th Action
            tbody
              = render @posts
        = pagination @posts, 'bootstrap4'

app/views/admin/posts/new.html.slim
h1.mt-4 NEW USER
ol.breadcrumb.mb-4
  li.breadcrumb-item = link_to 'Admin Page', admin_path
  li.breadcrumb-item = link_to 'List Of Users', admin_users_path
  li.breadcrumb-item.active New User
= render 'form', user: @user

app/views/admin/shared/_footer.html.slim
footer.py-4.bg-light.mt-auto
  .container-fluid.px-4
    .d-flex.align-items-center.justify-content-between.small
      .text-muted Copyright © Your Website 2021
      div
        a href="#"  Privacy Policy
        | ·
        a href="#"  Terms &amp; Conditions

app/views/admin/shared/_navbar.html.slim
nav.sb-topnav.navbar.navbar-expand.navbar-dark.bg-dark
  /! Navbar Brand
  a.navbar-brand.ps-3 href="#"  Start Bootstrap
  /! Sidebar Toggle
  button#sidebarToggle.btn.btn-link.btn-sm.order-1.order-lg-0.me-4.me-lg-0 href="#!"
    i.fas.fa-bars
  .d-none.d-md-inline-block.form-inline.ms-auto.me-0.me-md-3.my-2.my-md-0
  /! Navbar
  ul.navbar-nav.ms-auto.ms-md-0.me-3.me-lg-4
    li.nav-item.dropdown
      a#navbarDropdown.nav-link.dropdown-toggle aria-expanded="false" data-bs-toggle="dropdown" href="#" role="button"
        i.fas.fa-user.fa-fw
      ul.dropdown-menu.dropdown-menu-end aria-labelledby="navbarDropdown"
        li
          = link_to 'Logout', destroy_user_session_path, class: 'dropdown-item', data: { confirm: 'Are you sure ?' }, method: :delete

app/views/admin/shared/_sidebar.html.slim
#layoutSidenav_nav
  nav#sidenavAccordion.sb-sidenav.accordion.sb-sidenav-dark
    .sb-sidenav-menu
      .nav
        = link_to root_path, class: 'nav-link' do
          .sb-nav-link-icon
            i.fas.fa-arrow-left
          | Back To Home Page
        .sb-sidenav-menu-heading Management
        = link_to admin_users_path, class: 'nav-link' do
          .sb-nav-link-icon
            i.fas.fa-users
          | Users
        = link_to admin_posts_path, class: 'nav-link' do
          .sb-nav-link-icon
            i.fas.fa-blog
          | Posts
        / .sb-sidenav-menu-heading Interface
        / a.nav-link.collapsed aria-controls="collapseLayouts" aria-expanded="false" data-bs-target="#collapseLayouts" data-bs-toggle="collapse" href="#" 
        /   .sb-nav-link-icon
        /     i.fas.fa-columns
        /   | Layouts
        /   .sb-sidenav-collapse-arrow
        /     i.fas.fa-angle-down
        / #collapseLayouts.collapse aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion" 
        /   nav.sb-sidenav-menu-nested.nav
        /     a.nav-link href="layout-static.html"  Static Navigation
        /     a.nav-link href="layout-sidenav-light.html"  Light Sidenav
        / a.nav-link.collapsed aria-controls="collapsePages" aria-expanded="false" data-bs-target="#collapsePages" data-bs-toggle="collapse" href="#" 
        /   .sb-nav-link-icon
        /     i.fas.fa-book-open
        /   | Pages
        /   .sb-sidenav-collapse-arrow
        /     i.fas.fa-angle-down
        / #collapsePages.collapse aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion" 
        /   nav#sidenavAccordionPages.sb-sidenav-menu-nested.nav.accordion
        /     a.nav-link.collapsed aria-controls="pagesCollapseAuth" aria-expanded="false" data-bs-target="#pagesCollapseAuth" data-bs-toggle="collapse" href="#" 
        /       | Authentication
        /       .sb-sidenav-collapse-arrow
        /         i.fas.fa-angle-down
        /     #pagesCollapseAuth.collapse aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages" 
        /       nav.sb-sidenav-menu-nested.nav
        /         a.nav-link href="login.html"  Login
        /         a.nav-link href="register.html"  Register
        /         a.nav-link href="password.html"  Forgot Password
        /     a.nav-link.collapsed aria-controls="pagesCollapseError" aria-expanded="false" data-bs-target="#pagesCollapseError" data-bs-toggle="collapse" href="#" 
        /       | Error
        /       .sb-sidenav-collapse-arrow
        /         i.fas.fa-angle-down
        /     #pagesCollapseError.collapse aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages" 
        /       nav.sb-sidenav-menu-nested.nav
        /         a.nav-link href="401.html"  401 Page
        /         a.nav-link href="404.html"  404 Page
        /         a.nav-link href="500.html"  500 Page
    .sb-sidenav-footer
      .small Logged in as:
      = current_user.name

app/views/admin/users/_form.html.slim
- content_for(:header) do
  = stylesheet_link_tag 'admin/users/form', media: 'all'

.row
  .col-xl-12
    .card
      .card-body
        = form_with model: [:admin, user], local: true do |f|
          .card-body
            .form-floating.mb-3
              = f.text_field :name, class: 'form-control', id: 'inputName', autocomplete: 'off', required: true
              label for='inputName' User Name #{user.errors[:name].join('and')}
            .form-floating.mb-3
              = f.email_field :email, class: 'form-control', autocomplete: 'off', id: 'inputEmail', required: true
              label for='inputEmail' Email address #{user.errors[:email].join('and')}
            .form-floating.mb-3
              = f.password_field :password, class: 'form-control', id: 'inputPassword'
              label for='inputPassword' Password #{user.errors[:password].join('and')}
            => f.submit 'Submit', class: 'btn btn-primary'
            = link_to 'Back', admin_users_path, class: 'btn btn-secondary'

app/views/admin/users/_user.html.slim
tr
  td = user.id
  td = user.name
  td = user.email
  td = l user.created_at, format: :default
  td
    => link_to 'Edit', edit_admin_user_path(user), class: 'btn btn-warning'
    = link_to 'Destroy', admin_user_path(user), class: 'btn btn-danger', data: { confirm: 'Are you sure ?' }, method: :delete

app/views/admin/users/edit.html.slim
h1.mt-4 EDIT USER
ol.breadcrumb.mb-4
  li.breadcrumb-item = link_to 'Admin Page', admin_path
  li.breadcrumb-item = link_to 'List Of Users', admin_users_path
  li.breadcrumb-item.active Edit User
= render 'form', user: @user

app/views/admin/users/index.html.slim
h1.mt-4 LIST OF USERS
ol.breadcrumb.mb-4
  li.breadcrumb-item = link_to 'Admin Page', admin_path
  li.breadcrumb-item.active List Of Users
.row
  .col-xl-12
    .card.mb-4
      .card-header
        .float-end
          = link_to 'New User', new_admin_user_path, class: 'btn btn-primary'
      .card-body
        = pagination @users, 'bootstrap4'
        .table-responsive
          table.table.table-bordered.table-striped.text-nowrap
            thead
              tr
                th Id
                th Name
                th Email
                th Created at
                th Action
            tbody
              = render @users
        = pagination @users, 'bootstrap4'

app/views/home/index.html.slim
header.masthead style=("background-image: url(#{asset_path 'home-bg.jpg'})")
  .container.position-relative.px-4.px-lg-5
    .row.gx-4.gx-lg-5.justify-content-center
      .col-md-10.col-lg-8.col-xl-7
        .site-heading
          h1 Clean Blog
          span.subheading A Blog Theme by Start Bootstrap
.container.px-4.px-lg-5
  .row.gx-4.gx-lg-5.justify-content-center
    .col-md-10.col-lg-8.col-xl-7
      - if @posts.present?
      = render @posts
      = pagination @posts, 'custom_theme'

app/views/layouts/application.html.slim
doctype html
html
  head
    title SimpleApp
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta charset="utf-8" /
    meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport" /
    meta content="" name="description" /
    meta content="" name="author" /
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = yield :header
  body
    = render 'shared/navbar'
    = yield
    = render 'shared/footer'

app/views/layouts/application_authentication.html.slim
doctype html
html
  head
    title SimpleApp
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta charset="utf-8" /
    meta content="IE=edge" http-equiv="X-UA-Compatible" /
    meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport" /
    meta content="" name="description" /
    meta content="" name="author" /
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'admin/application', media: 'all'
    = javascript_include_tag 'admin/application'
    = yield :header
  body.bg-primary
    #layoutAuthentication
      #layoutAuthentication_content
        main
          .container
            .row.justify-content-center
              = yield
      #layoutAuthentication_footer
        footer.py-4.bg-light.mt-auto
          .container-fluid.px-4
            .d-flex.align-items-center.justify-content-between.small
              .text-muted Copyright © Your Website 2021
              div
                a href="#"  Privacy Policy
                | ·
                a href="#"  Terms &amp; Conditions

app/views/posts/_form.html.slim
- content_for(:header) do
  = stylesheet_link_tag 'shared/posts/form'
  = javascript_include_tag Ckeditor.cdn_url
  = javascript_include_tag 'shared/posts/form'

= form_with model: post, local: true do |f|
  .form-floating
    = f.text_field :title, class: 'form-control', id: 'inputTitle', placeholder: 'Title', autocomplete: 'off', required: true
    label for='inputTitle' Title #{post.errors[:title].join('and')}
  .form-floating
    = f.text_field :description, class: 'form-control', placeholder: 'Description', autocomplete: 'off', id: 'inputDescription'
    label for='inputDescription' Description #{post.errors[:description].join('and')}
  .form-floating.d-flex.flex-column-reverse
    - if post.header_image.present?
      = image_tag post.header_image.thumb.url, class: 'mb-1', id: 'previewImage'
    - else
      img.mb-1#previewImage src="#{asset_path 'default-image.jpg'}"
    = f.file_field :header_image, class: 'form-control pt-1', id: 'inputHeaderImage'
    label.position-static for='inputHeaderImage' Header Image #{post.errors[:header_image].join('and')}
  .form-floating.d-flex.flex-column-reverse
    = f.cktext_area :content, class: 'form-control', placeholder: 'Content', autocomplete: 'off', id: 'inputContent', required: true
    label.position-static for='inputContent' Content #{post.errors[:content].join('and')}
  .form-check.my-3
    = f.check_box :published, class: 'form-check-input', id: 'checkPublished'
    label.form-check-label for="checkPublished"  Published Now
  => f.submit 'Submit', class: 'btn btn-primary'
  = link_to 'Back', posts_path, class: 'btn btn-secondary'

app/views/posts/_post.html.slim
.post-preview
  = link_to post_path(post) do
    h2.post-title = post.title
    h3.post-subtitle = post.description
  - if post.published.present?
    p.post-meta
      = "Published on #{l post.published_at, format: :without_time}"

app/views/posts/edit.html.slim
header.masthead style=("background-image: url(#{asset_path 'home-bg.jpg'})")
  .container.position-relative.px-4.px-lg-5
    .row.gx-4.gx-lg-5.justify-content-center
      .col-md-10.col-lg-8.col-xl-7
        .site-heading
          h1 Edit Post
main.mb-4
  .container.px-4.px-lg-5
    .row.gx-4.gx-lg-5.justify-content-center
      .col-md-10.col-lg-8.col-xl-7
        .my-5
          = render 'form', post: @post

app/views/posts/index.html.slim
header.masthead style=("background-image: url(#{asset_path 'home-bg.jpg'})")
  .container.position-relative.px-4.px-lg-5
    .row.gx-4.gx-lg-5.justify-content-center
      .col-md-10.col-lg-8.col-xl-7
        .site-heading
          h1 = current_user.name
          span.subheading = current_user.email
.container.px-4.px-lg-5
  .row.gx-4.gx-lg-5.justify-content-center
    .col-md-10.col-lg-8.col-xl-7
      .d-flex.justify-content-start.mb-4
        = link_to 'Create New Post', new_post_path, class: 'btn btn-warning text-uppercase'
      - if @posts.present?
        hr.my-4/
      = render @posts
      = pagination @posts, 'custom_theme'

app/views/posts/new.html.slim
header.masthead style=("background-image: url(#{asset_path 'blog.jpg'})")
  .container.position-relative.px-4.px-lg-5
    .row.gx-4.gx-lg-5.justify-content-center
      .col-md-10.col-lg-8.col-xl-7
        .site-heading
          h1 Create Post
main.mb-4
  .container.px-4.px-lg-5
    .row.gx-4.gx-lg-5.justify-content-center
      .col-md-10.col-lg-8.col-xl-7
        .my-5
          = render 'form', post: @post

app/views/posts/show.html.slim
header.masthead style=("background-image: url(#{asset_path(@post.header_image.present? ? @post.header_image.url : 'home-bg.jpg')})")
  .container.position-relative.px-4.px-lg-5
    .row.gx-4.gx-lg-5.justify-content-center
      .col-md-10.col-lg-8.col-xl-7
        .post-heading
          h1 = @post.title
          h2.subheading = @post.description
          span.meta
            | Posted by 
            a href="#!" = @post.user_name
            - if @post.published_at.present?
              = " on #{l @post.published_at, format: :without_time}"
article.mb-4
  .container.px-4.px-lg-5
    .row.gx-4.gx-lg-5.justify-content-center
      .col-md-10.col-lg-8.col-xl-7.overflow-auto
        - if policy(@post).publish?
          .d-flex.justify-content-between.mb-4
            => link_to 'Edit Post', edit_post_path(@post), class: 'btn btn-warning text-uppercase'
            = link_to 'Publish This Post', publish_post_path(@post), class: 'btn btn-success text-uppercase', method: :post unless @post.published
          hr.my-4/
        = @post.content.html_safe

app/views/shared/_error_messages.html.slim
- if resource.errors.any?
  ul#error_explanation
    - resource.errors.full_messages.each do |message|
      li.text-danger = message

app/views/shared/_flash_messages.html.slim
.flash-message
  - flash.each do |message_type, message|
    ul class=('mb-3')
      li class=("#{message_type == 'alert' ? 'text-danger' : 'text-success'}") = message

app/views/shared/_footer.html.slim
footer.border-top
  .container.px-4.px-lg-5
    .row.gx-4.gx-lg-5.justify-content-center
      .col-md-10.col-lg-8.col-xl-7
        ul.list-inline.text-center
          li.list-inline-item
            a href="#!"
              span.fa-stack.fa-lg
                i.fas.fa-circle.fa-stack-2x
                i.fab.fa-twitter.fa-stack-1x.fa-inverse
          li.list-inline-item
            a href="#!"
              span.fa-stack.fa-lg
                i.fas.fa-circle.fa-stack-2x
                i.fab.fa-facebook-f.fa-stack-1x.fa-inverse
          li.list-inline-item
            a href="#!"
              span.fa-stack.fa-lg
                i.fas.fa-circle.fa-stack-2x
                i.fab.fa-github.fa-stack-1x.fa-inverse
        .small.text-center.text-muted.fst-italic Copyright © Your Website 2021

app/views/shared/_navbar.html.slim
nav#mainNav.navbar.navbar-expand-lg.navbar-light
  .container.px-4.px-lg-5
    a.navbar-brand href=""  Start Bootstrap
    button.navbar-toggler aria-controls="navbarResponsive" aria-expanded="false" aria-label=("Toggle navigation") data-bs-target="#navbarResponsive" data-bs-toggle="collapse" type="button"
      | Menu
      i.fas.fa-bars
    #navbarResponsive.collapse.navbar-collapse
      ul.navbar-nav.ms-auto.py-4.py-lg-0
        - if user_signed_in? && current_user.admin?
          li.nav-item
            = link_to 'Admin Page', admin_path, class: 'nav-link px-lg-3 py-3 py-lg-4'
        li.nav-item
          = link_to 'Home', root_path, class: 'nav-link px-lg-3 py-3 py-lg-4'
        - if user_signed_in?
          li.nav-item
            = link_to 'My Posts', posts_path, class: 'nav-link px-lg-3 py-3 py-lg-4'
        li.nav-item
          - if user_signed_in?
            = link_to 'Logout', destroy_user_session_path, class: 'nav-link px-lg-3 py-3 py-lg-4', data: { confirm: 'Are you sure ?' }, method: :delete
          - else
            = link_to 'Login', new_user_session_path, class: 'nav-link px-lg-3 py-3 py-lg-4'